#page title
page_title                                : My Daily Calories - Fimbl                     # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6443701726                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app_icon.png                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : My Daily Calories - Fimbl                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : My Daily Calories - Fimbl is a free, easy-to-use app that helps you track your calorie intake and log your weight. With a database of over 2 million products, you can search or scan items to add to your daily intake and follow your progress over time.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : AppRise Ventures                                
company_id                                : 3336104-8                                 
your_link                                 :                      
your_city                                 : Finland                                
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Track calorie consumption
    description                           : Easily add and track the calories you consume on a daily basis
    fontawesome_icon_name                 : utensils
  
  - title                                 : Track body weight
    description                           : Keep track of your weight over time and see your progress with charts and graphs
    fontawesome_icon_name                 : calendar-days
    
  - title                                 : Over 2 million food products
    description                           : Choose from a huge database of food products to add to your diary
    fontawesome_icon_name                 : book

  - title                                 : Stay on Track
    description                           : Follow your progress and stay motivated with Fimbl's tracking features
    fontawesome_icon_name                 : chart-line

  - title                                 : Quickly search food products
    description                           : Scan barcodes with your phone's camera to quickly search and add items to your diary
    fontawesome_icon_name                 : barcode

  - title                                 : Free to Use
    description                           : Fimbl is completely free to use, so you can focus on reaching your health goals
    fontawesome_icon_name                 : tag

  - title                                 : Personalized Goals
    description                           : Set and track personalized goals to help you reach your specific health objectives
    fontawesome_icon_name                 : award

  - title                                 : Available as an App
    description                           : Download easy-to-use app from App Store or Android Play
    fontawesome_icon_name                 : mobile-screen

  - title                                 : Easy to use
    description                           : Our app is designed to be simple and straightforward, with no unnecessary features to get in your way
    fontawesome_icon_name                 : check

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.2
topbar_title_color                        : "#ffffff"

cover_image                               : assets/fimbl_bg.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#5951D4"
cover_overlay_transparency                : 0

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#5951D4"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
